2018-05-09 20:02:08,189 ERROR: Exception on /emailpost/7 [GET] [in c:\users\castle\documents\microblog\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Castle\Documents\microblog\app\routes.py", line 162, in emailpost
    send_post(user, postid)
NameError: name 'send_post' is not defined
2018-05-09 20:02:57,009 INFO: Microblog startup [in C:\Users\Castle\Documents\microblog\app\__init__.py:48]
2018-05-09 20:03:01,694 ERROR: Exception on /emailpost/7 [GET] [in c:\users\castle\documents\microblog\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Castle\Documents\microblog\app\routes.py", line 162, in emailpost
    send_post(user, postid)
  File "C:\Users\Castle\Documents\microblog\app\email.py", line 36, in send_post
    recipients=[user.email],
AttributeError: 'function' object has no attribute 'email'
2018-05-09 20:04:10,755 INFO: Microblog startup [in C:\Users\Castle\Documents\microblog\app\__init__.py:48]
2018-05-09 20:14:34,554 INFO: Microblog startup [in C:\Users\Castle\Documents\microblog\app\__init__.py:48]
2018-05-09 20:16:44,492 INFO: Microblog startup [in C:\Users\Castle\Documents\microblog\app\__init__.py:48]
2018-05-09 20:18:31,623 INFO: Microblog startup [in C:\Users\Castle\Documents\microblog\app\__init__.py:48]
2018-05-09 20:20:55,124 INFO: Microblog startup [in C:\Users\Castle\Documents\microblog\app\__init__.py:48]
2018-05-09 20:22:56,193 INFO: Microblog startup [in C:\Users\Castle\Documents\microblog\app\__init__.py:48]
2018-05-09 20:52:56,835 INFO: Microblog startup [in C:\Users\Castle\Documents\microblog\app\__init__.py:48]
2018-05-09 20:52:58,820 ERROR: Exception on /emailpost/7 [GET] [in c:\users\castle\documents\microblog\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Castle\Documents\microblog\app\routes.py", line 162, in emailpost
    send_post(current_user, postid)
  File "C:\Users\Castle\Documents\microblog\app\email.py", line 40, in send_post
    user=user))
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Castle\Documents\microblog\app\templates\email\send_post.html", line 6, in top-level template code
    {{post.id}}
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'post' is undefined
2018-05-09 20:58:50,357 INFO: Microblog startup [in C:\Users\Castle\Documents\microblog\app\__init__.py:48]
2018-05-09 20:58:58,264 INFO: Microblog startup [in C:\Users\Castle\Documents\microblog\app\__init__.py:48]
2018-05-09 20:59:05,727 ERROR: Exception on /emailpost/7 [GET] [in c:\users\castle\documents\microblog\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Castle\Documents\microblog\app\routes.py", line 163, in emailpost
    send_post(current_user, post2send)
  File "C:\Users\Castle\Documents\microblog\app\email.py", line 40, in send_post
    user=user))
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Castle\Documents\microblog\app\templates\email\send_post.html", line 6, in top-level template code
    {{post2send.id}}
  File "c:\users\castle\documents\microblog\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'post2send' is undefined
2018-05-09 21:00:02,980 INFO: Microblog startup [in C:\Users\Castle\Documents\microblog\app\__init__.py:48]
